[features]
seeds = false
skip-lint = false
[programs.localnet]
donation_dapp = "BNLeVGT6zY4QBQfJe1NV1PFUQHik3rNyBm8d9A2fNnCY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yashjain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
